[package]
name = "xtask_lintdoc"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
xtask = { path = '../', version = "0.0" }
tuna_analyze = { path = "../../crates/tuna_analyze" }
tuna_console = { path = "../../crates/tuna_console" }
tuna_diagnostics = { path = "../../crates/tuna_diagnostics" }
tuna_js_analyze = { path = "../../crates/tuna_js_analyze" }
tuna_json_analyze = { path = "../../crates/tuna_json_analyze" }
tuna_js_parser = { path = "../../crates/tuna_js_parser" }
tuna_js_syntax = { path = "../../crates/tuna_js_syntax" }
tuna_json_parser = { path = "../../crates/tuna_json_parser" }
tuna_json_syntax = { path = "../../crates/tuna_json_syntax" }
tuna_service = { path = "../../crates/tuna_service" }
tuna_formatter = { path = "../../crates/tuna_formatter" }
pulldown-cmark = { version = "0.9", default-features = false }
