[package]
authors.workspace    = true
edition.workspace    = true
license.workspace    = true
name                 = "tuna_formatter_test"
repository.workspace = true
version              = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
insta            = { workspace = true, features = ["glob"] }
tuna_console     = { workspace = true }
tuna_diagnostics = { workspace = true }
tuna_formatter   = { workspace = true }
tuna_fs          = { workspace = true }
tuna_parser      = { workspace = true }
tuna_rowan       = { workspace = true }
tuna_service     = { workspace = true }
serde            = { version = "1", features = ["derive"] }
serde_json       = { workspace = true }
similar          = "2.1.0"
similar-asserts  = "1.2.0"

[dev-dependencies]
