[package]
authors.workspace    = true
edition.workspace    = true
license.workspace    = true
name                 = "tuna_js_analyze"
repository.workspace = true
version              = "0.0.0"

[dependencies]
bpaf.workspace        = true
lazy_static           = { workspace = true }
natord                = "1.0.9"
roaring               = "0.10.1"
tuna_analyze          = { workspace = true }
tuna_aria             = { workspace = true }
tuna_console          = { workspace = true }
tuna_control_flow     = { workspace = true }
tuna_deserialize      = { workspace = true }
tuna_diagnostics      = { workspace = true }
tuna_js_factory       = { workspace = true }
tuna_js_semantic      = { workspace = true }
tuna_js_syntax        = { workspace = true }
tuna_js_unicode_table = { workspace = true }
tuna_json_factory     = { workspace = true }
tuna_json_syntax      = { workspace = true }
tuna_rowan            = { workspace = true }
rustc-hash            = { workspace = true }
schemars              = { workspace = true, optional = true }
serde                 = { workspace = true, features = ["derive"] }
serde_json            = { workspace = true }
smallvec              = { workspace = true }

[dev-dependencies]
countme         = { workspace = true, features = ["enable"] }
insta           = { workspace = true, features = ["glob"] }
tuna_js_parser  = { workspace = true, features = ["tests"] }
tuna_test_utils = { workspace = true }
tuna_text_edit  = { workspace = true }
tests_macros    = { workspace = true }

[features]
schema = ["schemars", "tuna_deserialize/schema"]
